[[$head?&style=`1`&media=`1`&vik=`1`&main=`1`&classes=`article_one`]]
<section class="sect sect0 sect-heads" id="sect0">
    <header class="headers"
            style="background: url([[*main_article_photo]])no-repeat center;">
        [[!pdoCrumbs?
        &tplHome=`@INLINE
        <li><a href="[[++site_url]]"><img
                        src="/assets/img/homee.png" alt="">home</a>
        </li>
        `
        &showHome=`1`
        &showAtHome=`0`
        ]]
        <div class="back-head"><img src="/assets/img/back.png" alt="">back</div>

        <div class="numb">
            <div class="numbers numb1"><div class="hd" style="width: 86px;"><span>01.</span></div></div>
            <div class="numbers numb2"><div class="hd" style="width: 0px;"><span>02.</span></div></div>
            <div class="numbers numb3"><div class="hd" style="width: 0px;"><span>03.</span></div></div>
            <div class="numbers numb4"><div class="hd" style="width: 0px;"><span>04.</span></div></div>
        </div>
        <div class="head-leter">[[*pagetitle]]</div>

        <div class="main-menu">
            <ul>
                [[$main_menu]]
            </ul>
        </div>
        <div class="wrap-lines9">
            <div class="wrap-container5">
                <div class="line line1">
                    <div class="white-line"></div>
                </div>
                <div class="line line2">
                    <div class="white-line"></div>
                </div>
                <div class="line line3">
                    <div class="white-line"></div>
                </div>
                <div class="line line4">
                    <div class="white-line"></div>
                    <div class="white-line9"></div>
                </div>
            </div>
        </div>
        <div class="head-line">

            <div class="logo">
                <a href="/">
                    <img src="/assets/img/logo.png" alt="">
                    <img class="inverted-logo" src="/assets/img/logo-i.png">
                </a>
            </div>
            <div class="lang lang-mark">
                <div class="lang-block">
                    <ul>
                        [[$lang_block]]
                    </ul>
                </div>
            </div>
            <div class="menu">
                <div class="cross-menu">
                    <div class="cross-obj">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </div>
            </div>
            <div class="langy">
                <div class="lang-block">
                    <ul>
                        [[$lang_block]]
                    </ul>
                </div>
            </div>

        </div>
        <div class="comment">
            <div class="watt"><img src="/assets/img/watt.png" alt="">1423
            </div>
            <div class="watt"><img src="/assets/img/lett.png" alt="">223
            </div>
        </div>
    </header>

</section>

<div class="main">
    <div class="wrap-lines"><div class="wrap-container"><div class="line line0 active"></div><div class="line line1 active"></div><div class="line line2"></div><div class="line line3"></div><div class="line line4"></div><div class="line line5"></div></div></div>

    <section class="sect sectt1">
        <div class="container">
            <div class="boom">[[*section1_text]]</div>
        </div>
    </section>

    <div class="sect ">
        <div class="container">
            <div class="boom">
                <div class="boom-carr">
                    <img src="/assets/img/boom.png" alt="">
                    <div class="playy">
                        <img src="/assets/img/play5.png" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>

    [[*section2_text:!empty=`
    <section class="sect sectt2">
        <div class="container">
            <div class="renderer">[[*section2_text]]</div>
        </div>
    </section>
    `]]

    <section class="sect hire-wrapper">
        <div class="container">
            <div class="hire">
                [[!getImageList?
                &docid=`[[*id]]`
                &tvname=`migx_hire_collection`
                &tpl=`@CODE:
                <div class="onee-hire">
                    <div class="howw howw1">
                        <div class="howw-img">
                            <div class="tenn"></div>
                            <div class="tenn9"></div>
                            <img src="[[+image]]" alt="[[+alt]]"
                                 title="[[+img_title]]">
                        </div>
                    </div>
                    <div class="howw howw2">
                        <div class="howw-hire">
                            <div class="hire-block">
                                <h4>[[+title]]</h4>
                                <p>[[+text]]</p>
                            </div>
                        </div>
                    </div>
                </div>
                `
                &tpl_n2=`@CODE:
                <div class="twoo-hire">
                    <div class="howw">
                        <div class="howw-hire">
                            <div class="hire-block">
                                <h4>[[+title]]</h4>
                                <p>[[+text]]</p>
                            </div>
                        </div>
                    </div>
                    <div class="howw">
                        <div class="howw-img">
                            <div class="tenn"></div>
                            <div class="tenn9"></div>
                            <img src="[[+image]]" alt="[[+alt]]"
                                 title="[[+img_title]]">
                        </div>
                    </div>
                </div>
                `
                ]]
                <div class="clear"></div>

            </div>
        </div>
    </section>

    [[*section3_text:!empty=`
    <section class="sect">
        <div class="container">
            <div class="renderer rend">[[*section3_text]]</div>
        </div>
    </section>
    `]]

    <section class="sect">
        <div class="container">
            <div class="share5">
                <div class="onee-share">
                    Share:
                </div>
                <div class="twoo-share">
                    <img src="/assets/img/face.png" alt=""><span>414</span>
                </div>
                <div class="three-share">
                    <img src="/assets/img/insta.png" alt=""><span>23</span>
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </section>

    <section class="sect disqus">
        <div class="container">
            <div id="disqus_thread"></div>
        </div>
    </section>


    <section class="sect sectt3">
        <div class="container">
            <div class="arti">
                <h3>Articles on virtual reality</h3>
                [[!pdoResources?
                &parents=`[[*parent]]`
                &resources=`-[[*id]]`
                &includeTVs=`article_image,article_desc`
                &tvPrefix=``
                &sortby=`RAND()`
                &tpl=`article_item_tpl`
                &where=`{"template":5}`
                &limit=`4`
                &showLog=`0`
                ]]
                <div class="clear"></div>
            </div>
        </div>
        <div class="fresh">
            <a href="javascript:void(0);">
                <img src="/assets/img/fresh.png" alt="">
            </a>
        </div>
    </section>
    <div class="texy"><img src="/assets/img/arrr.png" alt=""></div>

</div>

[[$menus_open]]

<script src="/assets/js/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/1.20.2/TweenLite.min.js"></script>
<script src="http://cdn.jsdelivr.net/jquery.mcustomscrollbar/3.1.5/jquery.mCustomScrollbar.min.js"></script>
<script src="/assets/js/vik.js"></script>
<script src="/assets/js/nice.js"></script>
<script src="/assets/js/comon.js"></script>

<script>

    /**
     *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
     *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
    /*
    var disqus_config = function () {
    this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    */
    (function() { // DON'T EDIT BELOW THIS LINE

        var d = document, s = d.createElement('script');
        s.src = 'https://http-38-j2landing-com.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

</body>
</html>