[[$head?
&mScrollbar=`1`
&style=`1`
&media=`1`
&vik=`1`
&classes=`home-page`
]]

<section class="sect sect0" id="sect0">

    <header class="headers">

        <div class="mobil"><img src="/assets/img/woman.png" alt=""></div>
        <div class="mobil-name"><h1>[[*text1]]</h1></div>
        <div class="numb">
            <div class="numbers numb1">
                <div class="hd"><span>01.</span></div>
            </div>
            <div class="numbers numb2">
                <div class="hd"><span>02.</span></div>
            </div>
            <div class="numbers numb3">
                <div class="hd"><span>03.</span></div>
            </div>
            <div class="numbers numb4">
                <div class="hd"><span>04.</span></div>
            </div>

            <div class="numbers numb5">
                <div class="hd"><span>05.</span></div>
            </div>
            <div class="numbers numb5">
                <div class="hd"><span>06.</span></div>
            </div>
            <div class="numbers numb5">
                <div class="hd"><span>07.</span></div>
            </div>
            <div class="numbers numb5">
                <div class="hd"><span>08.</span></div>
            </div>
        </div>


        <div class="main-menu">
            <ul>
                [[$main_menu]]
            </ul>
        </div>
        <div class="fonn4"></div>
        <div class="divv-fonn">
            <div class="fonn"></div>
        </div>
        <div class="video-all-in">
            <div class="container-video">

                <div id="video">
                    <canvas id="bordersCanvas"
                            data-image="/assets/img/girl10.png" width="0"
                            height="0"></canvas>
                </div>
                <div id="video-butt">
                    <div class="head-text"><h1>[[*text1]]</h1></div>
                </div>
            </div>
        </div>
        <div class="wrap-lines9">
            <div class="wrap-container5">
                <div class="line line1">
                    <div class="white-line"></div>
                </div>
                <div class="line line2">
                    <div class="white-line"></div>
                </div>
                <div class="line line3">
                    <div class="white-line"></div>
                </div>
                <div class="line line4">
                    <div class="white-line"></div>
                    <div class="white-line9"></div>
                </div>
            </div>
        </div>
        <div class="head-line">
            <div class="logo"><a [[!getLink?&id=`[[++site_start]]`]]><img src="/assets/img/logo.png"
                                               alt=""></a></div>
            <div class="lang lang-mark" style="display:none;">
                <div class="lang-block">
                    <ul>
                        [[!BabelLinks?
                        &tpl=`babel_tpl`
                        &activeCls=`acti`
                        &showCurrent=`1`
                        ]]
                    </ul>
                </div>
            </div>
            <div class="menu" style="display:none;">
                <div class="cross-menu">

                    <div class="cross-obj">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </div>
            </div>
            <div class="langy" style="display:none;">
                <div class="lang-block">
                    <ul>
                        [[!BabelLinks?
                        &tpl=`babel_tpl`
                        &activeCls=`acti`
                        &showCurrent=`1`
                        ]]
                    </ul>
                </div>
            </div>

        </div>
    </header>
</section>
<div class="main">
    <div class="wrap-lines">
        <div class="wrap-container">
            <div class="line line0 active"></div>
            <div class="line line1 active"></div>
            <div class="line line2"></div>
            <div class="line line3"></div>
            <div class="line line4"></div>
            <div class="line line5"></div>
        </div>
    </div>
    <section class="sect sect01" id="sect01">
        <div class="container sect1">
            <div class="real">
                <div class="real-imgg"><img src="/assets/img/work.png" alt="">
                </div>
                <div class="virt">
                    <h2>[[*head2]]</h2>
                    <p>[[*text2:limit=`300`]]</p>
                </div>
                <div class="lead" style="display:none;"><a
                            href="javascript:void(0);" target="_blank">lead
                        more</a></div>
            </div>
        </div>

        <div class="container sect2">
            [[getImageList?
            &tvname=`section`
            &tpl=`tpl.sect2`

            &limit=`1`
            ]]
        </div>
    </section>


    <section class="sect sect02" id="sect02">
        <div class="container sect3">

            <div class="agmen">
                <div class="agren-imgg">
                    <div class="real-left"><img src="/assets/img/2.png" alt="">
                    </div>
                    <div class="lead" style="display:none;"><a
                                href="javascript:void(0);">lead more</a></div>
                </div>
                <div class="agren-word">

                    <h2>[[*head3]]</h2>
                    <p>[[*text3:limit=`300`]]</p></p>
                </div>
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
        </div>


        <div class="container sect4">


            [[getImageList?
            &tvname=`section3`

            &tpl=`tpl.sect3`
            &limit=`1`
            ]]
        </div>
    </section>


    <section class="sect sect03" id="sect03">
        <div class="container sect5">
            <div class="real">
                <div class="real-imgg"><img src="/assets/img/3.png" alt="">
                </div>
                <div class="virt">
                    <h2>[[*head4]]</h2>
                    <p>[[*text4:limit=`300`]]</p>
                </div>
                <div class="lead" style="display:none;"><a
                            href="javascript:void(0);">lead more</a></div>
            </div>
        </div>
        <div class="clear"></div>
        <div class="container sect6">

            [[getImageList?
            &tvname=`section4`

            &tpl=`tpl.sect4`
            &limit=`1`
            ]]
        </div>
        <div class="clear"></div>
    </section>


    <section class="sect sect04" id="sect04">
        <div class="container sect7">
            <div class="lira"></div>
            <div class="agmen">
                <div class="agren-imgg">
                    <div class="real-left"><img src="/assets/img/4.png" alt="">
                    </div>
                    <div class="lead" style="display:none;"><a
                                href="javascript:void(0);">lead more</a></div>
                </div>
                <div class="agren-word">
                    <h2>[[*head5]]</h2>
                    <p>[[*text5:limit=`300`]]</p>


                </div>
                <div class="clear"></div>
            </div>
        </div>
        <div class="container sect8">
            [[getImageList?

            &tvname=`section5`
            &tpl=`tpl.sect5`
            &limit=`1`
            ]]
        </div>
    </section>

    <section class="sect sect9" id="sect9">
        <div class="container">
            <div class="about-block">
                <div class="aboou"><img src="/assets/img/page9.png" alt="">
                </div>
                <div class="about-text" style="padding:0 0 49px 0;">
                    <h3>[[*head07]]</h3>
                    [[*text07]]


                    <div class="more" style="display:none;"><a
                                href="javascript:void(0);">mores</a></div>
                </div>
                <div class="clear"></div>

                <div class="piple">

                    <div class="about-item">
                        <div class="glavn-item">
                            <div class="item-imgg"><img
                                        src="/assets/img/yaroslav.png" alt="">
                            </div>
                            <div class="item-text">
                                <div class="left-text">Yaroslav</div>
                                <div class="right-text">ceo</div>
                            </div>
                        </div>
                    </div>

                    <div class="about-item">
                        <div class="glavn-item">
                            <div class="item-imgg"><img
                                        src="/assets/img/elena.png" alt="">
                            </div>
                            <div class="item-text">
                                <div class="left-text">Elena</div>
                                <div class="right-text">Business Development
                                    Manager
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="about-item">
                        <div class="glavn-item">
                            <div class="item-imgg"><img
                                        src="/assets/img/olga.png" alt=""></div>
                            <div class="item-text">
                                <div class="left-text">Olga</div>
                                <div class="right-text">Key Account Manager
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="about-item">
                        <div class="glavn-item">
                            <div class="item-imgg"><img
                                        src="/assets/img/marya.png" alt="">
                            </div>
                            <div class="item-text">
                                <div class="left-text">Maria</div>
                                <div class="right-text"> 3D Artist</div>
                            </div>
                        </div>
                    </div>
                    <div class="about-item">
                        <div class="glavn-item">
                            <div class="item-imgg"><img
                                        src="/assets/img/vladislava.png" alt="">
                            </div>
                            <div class="item-text">
                                <div class="left-text">Vladyslava</div>
                                <div class="right-text">3D Artist</div>
                            </div>
                        </div>
                    </div>
                    <div class="about-item">
                        <div class="glavn-item">
                            <div class="item-imgg"><img
                                        src="/assets/img/myroslava.png" alt="">
                            </div>
                            <div class="item-text">
                                <div class="left-text">Myroslava</div>
                                <div class="right-text">Architect and
                                    Visualiser
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="about-item">
                        <div class="glavn-item">
                            <div class="item-imgg"><img
                                        src="/assets/img/yuriy.png" alt="">
                            </div>
                            <div class="item-text">
                                <div class="left-text">Yurii</div>
                                <div class="right-text">Architect and
                                    Visualiser
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="about-item">
                        <div class="glavn-item">
                            <div class="item-imgg"><img
                                        src="/assets/img/andriy.png" alt="">
                            </div>
                            <div class="item-text">
                                <div class="left-text">Andrey</div>
                                <div class="right-text">3D Modeler</div>
                            </div>
                        </div>
                    </div>
                    <div class="about-item">
                        <div class="glavn-item">
                            <div class="item-imgg"><img
                                        src="/assets/img/anna.png" alt=""></div>
                            <div class="item-text">
                                <div class="left-text">Anna</div>
                                <div class="right-text">Architect and
                                    Visualiser
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="clear"></div>
                </div>
            </div>
        </div>
    </section>
    <section class="sect sect10" id="sect10">
        <div class="container">

            <div class="article">
                [[getImageList?
                &tvname=`section07`

                &tpl=`tpl.sect6`
                &limit=`1`
                ]]
                <div class="arti" style="display:none;">

                    <h3>Articles</h3>
                    <div class="virtu">
                        <div class="left-virt"><img
                                    src="/assets/img/articels_1.png" alt="">
                            <div class="lead-more">lead more</div>
                            <div class="mess">
                                <div class="left-mess"><span>223</span><img
                                            src="/assets/img/mess.png" alt="">
                                </div>
                                <div class="right-mess"><span>223</span><img
                                            src="/assets/img/seen.png" alt="">
                                </div>
                            </div>
                        </div>
                        <div class="right-virt"><h4>VIRTUAL reality</h4>
                            <p>Step inside a premise and be able not only to
                                move your way through but also change materials,
                                colors, lighting, and even more...</p></div>
                    </div>

                    <div class="virtu">
                        <div class="left-virt"><img
                                    src="/assets/img/articels_1.png" alt="">
                            <div class="lead-more">lead more</div>
                            <div class="mess">
                                <div class="left-mess"><span>223</span><img
                                            src="/assets/img/mess.png" alt="">
                                </div>
                                <div class="right-mess"><span>223</span><img
                                            src="/assets/img/seen.png" alt="">
                                </div>
                            </div>
                        </div>
                        <div class="right-virt"><h4>VIRTUAL reality</h4>
                            <p>Step inside a premise and be able not only to
                                move your way through but also change materials,
                                colors, lighting, and even more...</p></div>
                    </div>
                    <div class="virtu">

                        <div class="left-virt"><img
                                    src="/assets/img/articels_1.png" alt="">
                            <div class="lead-more">lead more</div>
                            <div class="mess">
                                <div class="left-mess"><span>223</span><img
                                            src="/assets/img/mess.png" alt="">
                                </div>
                                <div class="right-mess"><span>223</span><img
                                            src="/assets/img/seen.png" alt="">
                                </div>
                            </div>
                        </div>


                        <div class="right-virt"><h4>VIRTUAL reality</h4>
                            <p>Step inside a premise and be able not only to
                                move your way through but also change materials,
                                colors, lighting, and even more...</p></div>
                    </div>
                    <div class="virtu">
                        <div class="left-virt"><img
                                    src="/assets/img/articels_1.png" alt="">
                            <div class="lead-more">lead more</div>
                            <div class="mess">
                                <div class="left-mess"><span>223</span><img
                                            src="/assets/img/mess.png" alt="">
                                </div>
                                <div class="right-mess"><span>223</span><img
                                            src="/assets/img/seen.png" alt="">
                                </div>
                            </div>
                        </div>
                        <div class="right-virt"><h4>VIRTUAL reality</h4>
                            <p>Step inside a premise and be able not only to
                                move your way through but also change materials,
                                colors, lighting, and even more...</p></div>
                    </div>

                    <div class="clear"></div>
                    <div class="more"><a href="javascript:void(0);"
                                         target="_blank">more articles</a></div>
                </div>
            </div>
        </div>
    </section>
    <section class="sect sect07">

        <div class="container">
            <div class="contact">
                <h4>Contacts</h4>


                <div class="ofice">


                    <div class="adres">
                        <div class="left-adres"><p class="white">address</p>
                        </div>

                        <div class="right-adres"><p>[[#[[%8:bid]].address]]</p>
                        </div>
                    </div>

                    <div class="adres">
                        <div class="left-adres"><p class="white">telephones</p>
                        </div>


                        <div class="right-adres"><p>
                                [[#[[%8:bid]].telephones]]</p>
                            <p>[[#[[%8:bid]].telephone2]]</p></div>
                    </div>


                    <div class="adres">
                        <div class="left-adres"><p class="white">email</p></div>


                        <div class="right-adres"><p>[[#[[%8:bid]].email]]</p>
                        </div>
                    </div>
                    <div class="clear"></div>
                    <div class="link" style="display:none;">
                        <div class="block-link">
                            <div class="item-link"><a
                                        href="javascript:void(0);"><img
                                            src="/assets/img/face.png"
                                            alt=""></a></div>
                            <div class="item-link"><a
                                        href="javascript:void(0);"><img
                                            src="/assets/img/insta.png" alt=""></a>
                            </div>
                            <div class="item-link"><a
                                        href="javascript:void(0);"><img
                                            src="/assets/img/bebe.png"
                                            alt=""></a></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <footer class="footers">
            <div class="container">
                <div class="text-foot"><p>[[*seo_text]]</p>
                </div>
            </div>
            <div class="fresh"><a href="http://freshweb.agency/"><img
                            src="/assets/img/fresh.png" alt=""></a></div>
        </footer>
    </section>
    <div class="texy"><img src="/assets/img/leter.png" alt=""></div>
    [[$menus_open]]
</div>


<script src="/assets/js/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/1.20.2/TweenLite.min.js"></script>
<script src="http://cdn.jsdelivr.net/jquery.mcustomscrollbar/3.1.5/jquery.mCustomScrollbar.min.js"></script>
<script src="/assets/js/vik.js"></script>
<script src="/assets/js/nice.js"></script>
<script src="/assets/js/comon.js"></script>


</body>

</html>