[[$head?&vik=`1`&classes=`protfolio-item`]]
<header class="neww-headers">
    <div class="numb">
        <div class="numbers numb1" style="opacity: 0;">
            <div class="hd"><span>01.</span></div>
        </div>
        <div class="numbers numb2">
            <div class="hd"><span>01.</span></div>
        </div>
        <div class="numbers numb3">
            <div class="hd"><span>02.</span></div>
        </div>
    </div>
    <div class="main-menu">
        <ul>
            [[$main_menu]]
        </ul>
    </div>

    <div class="head-line">
        <div class="logo">
            <a href="[[++site_url]]">
                <img src="/assets/img/logo.png" alt="">
            </a>
        </div>
        <div class="lang lang-mark">
            <div class="lang-block">
                <ul>
                    [[$lang_block]]
                </ul>
            </div>
        </div>
        <div class="menu">
            <div class="cross-menu">
                <div class="cross-obj">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </div>
        </div>
        <div class="langy">
            <div class="lang-block">
                <ul>
                    [[$lang_block]]
                </ul>
            </div>
        </div>
    </div>
</header>
<div class="main">

    <div class="wrap-lines">
        <div class="wrap-container">
            <div class="line line0 active"></div>
            <div class="line line1 active"></div>
            <div class="line line2"></div>
            <div class="line line3"></div>
            <div class="line line4"></div>
            <div class="line line5"></div>
        </div>
    </div>


    <section class="sect sect0001">
        <div class="fonn-arti"></div>
        <div class="container">
            <div class="realism">
                <!--<div id="selectyBoxi">
                    <div class="closs"><img src="/assets/img/closy.png" alt="">
                    </div>
                    <p class="valueTags" name="selects">category</p>
                    <div class="clear"></div>
                    <ul id="selectyMenuBoxi">
                        <li class="options">virtual reality</li>
                        <li class="options">augmented reality</li>

                        <li class="options">virtual arhitects</li>
                    </ul>
                </div>-->

                <h1>[[*pagetitle]]</h1>
                <div class="realism-img">
                    <img src="[[*main_foto]]" alt="">
                </div>

                <div class="case-left">
                    <div class="case">
                        <h3>[[*case_number]]</h3>
                        <p>[[*case_desc]]</p>
                    </div>
                </div>
                <div class="case-right">
                    <div class="case-text">
                        [[*case_text]]
                    </div>
                </div>
                <div class="clear"></div>
                <div class="house-block">
                     [[*content_before_advant]]
                </div>

                [[$advantages_parent]]

                <div class="house-block">
                    [[*content_after_advant]]
                </div>
            </div>
        </div>
    </section>


    <section class="sect sect02" id="sect02">
        <div class="container">
            <div class="projects">
                <h3>Other projects</h3>
                <div class="collection-wraper">
                    [[!pdoResources?
                    &parents=`[[*parent]]`
                    &resources=`[[pdoResources? &resources=`-[[*id]]`
                    &sortby=`RAND()` &limit=`5` &returnIds=`1`]]`
                    &includeTVs=`port_main_img,double_size`
                    &tvPrefix=``
                    &tpl=`portfolio_item_tpl`
                    &showLog=`0`
                    &limit=`5`
                    ]]
                </div>
                <div class="lead"><a href="#">more articles</a></div>


                <div class="acqua">
                    [[$forma_tpl?&h3=`[[*lets_do_title]]`&text=`[[*lets_do_text]]`]]
                </div>
            </div>
        </div>
    </section>

    <div class="texy"><img src="/assets/img/karta-leter.png" alt=""></div>

</div>

[[$menus_open]]


<script src="/assets/js/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/1.20.2/TweenLite.min.js"></script>

<script src="http://cdn.jsdelivr.net/jquery.mcustomscrollbar/3.1.5/jquery.mCustomScrollbar.min.js"></script>
<script src="/assets/js/vik.js"></script>
<script src="/assets/js/nice.js"></script>
<script src="/assets/js/comon.js"></script>
</body>

</html>